# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sentence_text', models.CharField(max_length=2048)),
            ],
        ),
    ]
